### ISSUE TITLE
Find and Implement fast alghoritm for removing duplicate files

### ISSUE THREAD

**Issue by NullSingularity3** [kacperekk6/reddit-image-download#9]
As in title 

## TODO

- [x] - New branch, and WIP PR opened
- [x] - Unit tests created (TDD)
- [x] - Method for duplicate removal found XD
- [x] - Solution encapsulated

**Comment by NullSingularity3** [comment]
https://github.com/alessandrobelottidev/DuplicatesCleaner
